language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create:all
  - bundle exec rake db:migrate
before_script:
  - cp config/database.travis.yml config/database.yml
after_script:
  - rm config/database.yml
