development:
  adapter: postgresql
  host: localhost
  database: app-dev

test:
  adapter: postgresql
  host: localhost
  database: app-test

production:
  adapter: postgresql
  host: localhost
  database: app-prod
